### PR TITLE
Large Refactor to Match `mobx-angular` Codebase

### PR DESCRIPTION
**Pull request by nickbreaton**
Hello all. I have been working the past few days on a bunch of changes on my own branch. The main goal of this refactor is to bring the codebase to a parallel with [mobxjs/mobx-angular](https://github.com/mobxjs/mobx-angular).

The following are substantial changes:

1. Remove [`wrappedFunctions`](https://github.com/NgMobx/ng1-mobx/blob/master/lib/ng-mobx.js#L4) as they don't seem to be documented or used anywhere. 

2. Convert to TypeScript. 
    - MobX and mobx-angular is written in TS
    - If library grows, TS will help keep refactoring simple
    - Automatic definitions are generated on build 

3. Incorporate all of changes from @kuitos. This branch is forked from [here](https://github.com/mmlpxjs/mobx-angularjs). 

4. Replace the example with a much simpler one. Before it was an entire project that needed to be searched through for `mobx-autorun` directives. Now it is just a few files.

5. ~~Remove `angular` as a dependency and get it off the window.~~
    - ~~The official angular npm package attached `angular` to the window.~~
    - ~~Bower delivers npm in the same way.~~
    - ~~Other notable projects such as [ngRedux don't include it either](https://github.com/angular-redux/ng-redux/blob/master/package.json#L52-L61).~~

6. Add unit tests and CI. 
    - ~~This is still a work-in-progress~~, but IMO it is important for any library.
    - TravisCI will need to be pointed at this repo.

[Link to my branch.](https://github.com/nickbreaton/ng-mobx) Probably easiet to just look at codebase directly.

### CODE REVIEW

**Comment by kuitos** [comment]
Remove the angular dependency was not a good idea in my opinion. We should declare all the dependencies in `package.json` since the source code had referenced it, although `ngRedux` didn't follow this principle.
The bundle optimization requirement should be satisfied by bundler configuration such as webpack `externals` if we have, rather than realizing from the source code manually.

**Comment by nickbreaton** [comment]
I understand your point. It makes sense that if we are publishing to npm, we should depend on using npm dependencies and not worry about inter opt with bower or other systems, which was my original intent. I will update the PR when I get a moment.

**Comment by kuitos** [comment]
We need add a bundler for published package for several reasons, such as a directly script src usage.
But I think we can merge and rebase your major efforts and then improve it before we publish 2.0 version.

**Comment by nickbreaton** [comment]
Okay I am going to make a develop branch. We will merge this PR into that, and then start a new PR for the bundler. You can hit the merge button if you think it is ready.

**Pull request merged**
